# -*- coding: utf-8 -*-
"""Kohler_Assignment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aPekwK3e2IB3a4p2I5EB-zlv4UteOxr-
"""

# =================================
# Assignment 2 - simple calculator
# Name: Jonathan Kohler
# ID: 011165333
# =================================

num1 = int(input("Enter your first number: "))
num2 = int(input("Enter your second number: "))

def add():
  print("addition of input numbers:")
  x = int(num1 + num2)
  print (x, "\n")
  menu()

def sub():
  print ("Subtraction of input numbers:")
  x = int(num1 - num2)
  print (x, "\n")
  menu()

def mult():
  print ("Multiplication of input numbers:")
  x = int(num1 * num2)
  print (x, "\n")
  menu()

def div():
  print ("Division of input numbers: ", )
  x = float(num1 / num2)
  print (x, "\n")
  menu()
  
def powe():
  print ("%d to the power of %d is: " %(num1, num2))
  x = int(num1 ** num2)
  print (x, "\n")
  menu()
  
def mod():
  print ("modulo of input numbers: ")
  x = int(num1 % num2) 
  print (x, "\n")
  menu()

def WrongInput():
  print ("Wrong choice!")
  menu()

def SystemQuit():
  print ("system exiting...")
  sys.exit(1)

def menu():
  print (" ============\n Options:\n 1.	Add\n 2.	Subtract\n 3.	Multiply\n 4.	Divide\n 5.	Power\n 6.	Modulo\n==============\n Enter 'q' to exit system\n ")
  choice = input("choose a calculation option:\n")

  while True:
    if choice == '1':
      add()
    if choice == '2':
      sub()
    if choice == '3':
      mult()
    if choice == '4':
      div()
    if choice == '5':
      powe()
    if choice == '6':
      mod()
    if choice == "q":
      SystemQuit()
      break
    else:
      WrongInput()
      
menu()